<?php
/**
 * Created by PhpStorm.
 * Author: 火柴<290559038@qq.com>
 * Date: 2018/2/2
 * Time: 21:17
 */

namespace common\controller;


use Yii;
use yii\base\Module;

class FrontendController extends BaseController
{
    protected $user_info;

    public function __construct($id, Module $module, array $config = [])
    {
        parent::__construct($id, $module, $config);
       // var_dump(Yii::$app->user->identity);
        $this->user_info = Yii::$app->user->identity;
        // dump($this->user_info);
       // var_dump(Yii::$app->user->getIsGuest());
    }

    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
                'layout' => 'error', // <-- HERE
            ]
        ];
    }

    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


}